---
#This is the configuration file for the ItemCore plugin

#If the value of Enable is 'true' then the plugin will work
Enable: true #Default 'true'

#Below is the text that will be displayed when the player hold an item
#{x}, {y}, {z}, {world}, {direction}
#Use {x} to display the player's X coordinate
#Use {y} to display the player's Y coordinate
#Use {z} to display the player's Z coordinate
#Use {world} to display the name of the world the player is in
#Use {direction} to display the player's direction
Text: "§l§eX: §a{x}, §eY: §a{y}, §eZ: §a{z}\n§l§bWorld: §c{world}\n§l§6Direction: §d{direction}"

#Below is the Id of the Item you want the plugin to work on
ItemId: 345 #Id of Compass

#Below is format of direction
FormatSouth: South
FormatWest: West
FormatNorth: North
FormatEast: East
FormatNorthEast: NorthEast
FormatNorthWest: NorthWest
FormatSouthEast: SouthEast
FormatSouthWest: SouthWest

#Below is how it is displayed
#There are two type is: 'tip' and 'popup'
ShowType: tip #Default is 'tip'

#End of configuration file
...
